### ISSUE TITLE
Comments 

### ISSUE THREAD

**Issue by heyitsmerebecca** [ipsdm/legitimacy#3]
General notes: 

-According to my understanding of this repo, this structure can only be implemented in an already existing organization. “The goal of this section is to provide a comprehensive transition strategy from existing structures to the most legitimate structure conceivable.” It takes the assumption that there are already existing authorities and leadership. If the intention is to create an organization using this system “from scratch” then an implementation process must be created (and/or modifications to the existing one) to accommodate the not-yet existent hierarchy and leadership and all other necessary structures which need to be in place in order to implement the legitimacy process. So perhaps there should be an elucidation of all the necessary structures in the existing system which need to be in place before the implementation of this one. Based on the initialization steps in “Assessment”, there needs to be at least: existing organization leadership, existing organization authority, and members. 

-For use in this repo, what is the exact, clear distinction(s) between the the word “agreement” and “decision”? 

-“Within this utility, all members self-document all existing privileges and responsibilities currently held within the organization attempting to be as truthful and comprehensive as possible. At this point members should refrain from documenting what they would like their privileges and responsibilities to be but instead only focus on what privileges and responsibilities they truthfully already hold within the organization.”
There should be a strong form of check on any type of self reporting. I see this is in- “All organization members should now review and add suggestions to all other members self-documented privleges and responsibilities as well as suggested directives, agreements, and activities, for truthfulness as to closeness to approximation of the existing structure - again not in attempt to hone in on what is most ideal, but only to attempt to approximate what the existing structures/hierarchies truthfully are.” - if the voting privileges are dependent on a member’s privileges and/or responsibilities etc there must be a very formal review of all members’ self reported information. 

-“The goal of this section is to provide a comprehensive transition strategy from existing structures to the most legitimate structure conceivable. This transition period may take anywhere from a week to several years depending on the size of the organization.”
Size and complexity 

-“All members” - the use of “all members” in this repo refers to all members of the organization? If the organization is very complex and/or large in size, should “all members” be scaled down accordingly..? (Not for all, but for applicable measures)

-“All agreements should be made via the consensus process, any single disagreement on any element within any agreement is enough to bring that agreement into a state of contention.”
I think it is necessary should be some type of check on this. I understand it is one of the core elements of legitimacy but the way I see it, this “allowance” has potential to be easily abused. 

-What happens if a consensus cannot be reached through rational discourse and it is crucial to reach one (time is of essence etc). Does Moment of autocracy apply then? “In the absence of a viable means of arriving at consensus, mandating the use of consensus driven processes as described in this repository should be viewed as legitimate, but only for that particular moment.” - “in the absence of viable means at arriving at consensus” in the way I see it, this allowance must have very specific circumstances when it is allowed because it can easily be manipulated to an advantage or misconstrued. also, who is the authority who is allowed this privilege? Is it the highest authority within that organization or particular department of which the matter is concerned? That should be clarified. 

Notes on Part 1: “concept.md”: 
-Are the words “truthfully best” the most fitting for this situation?

-What (or who) constitutes “significantly affected?” are there particular guidelines, (if not should there be..?) 

-“self defense” needs more expounding 

-Non-malicious - I’m not familiar with the nuances of this term. Is there a chance of contention of “malicious intent”? if so, then further elaboration and specification would be needed. 

-“1. Those affected by decisions (stakeholders) are informed and have both a voice and weight in decision making.” - firstly, the “are informed” is a passive use of language, so is this intentional? Assuming those affected have a say in what they are being informed about? Is it the start of a decision or contention process? The usage of the words “are informed” may imply non involvement in the “being informed” process (when it is the members who are taking the first steps to start the process) Also, are these “stakeholders” the above mentioned “those significantly affected”? The usage of the same word description in both places might imply so. Who are the stakeholders? 

-“2. Consent must be gained from all those significantly affected by a decision in all situations independent of their membership in an organizational structure (aka all largely significant stakeholders have veto)” Similar issue as above, what constitutes “significantly affected”; is it the significant stakeholders, and if it is not specifically them, what is the set of specifications to be considered “significantly affected”. 
Also, the phrase “independent of their membership” - is it independent of their type of membership? the phrase may imply that, it should perhaps be expressed more clearly or elaborated. Is it perhaps that they should be involved in decisions even “outside” their membership? Perhaps I’m missing a detail here. 

-“3. Consensus is the primary mode of decision making whereby new alternative decision making mechanisms can be utilized legimately after having been agreed upon through the consensus process.” (Conceptual comment) So the new mechanism might not be (through) the process of consensus 
if the decision to change this process upholds itself in the decision making. [Which leads me to ask, what are the absolute core values of this structure that cannot be altered (to preserve this system of legitimacy?)]

-“4. All previously made decisions and agreements are subject to change through the contention process.” See above query. 

-“5. All agreements are documented  comprehensibly and explicitly.” perhaps “and are accessible to all members at all times” should be added. 

-“6. Agreements are enforceable among those who've agreed upon them.” 

-“7. All taken actions are non-malicious.” 

“The above suggested structure is a baseline structure which arbitrary further processes can be implemented within through further agreements.” Are these absolute core and cannot be altered? 

Notes on part 2: “definitions.md” 
Agreement: “A statement which has been agreed upon by all members of an organization according to the consensus process. In the context of this repository agreements are considered to be binding and documented statements which other decisions/agreements can be built upon.” 
In the “concept.md” file, “Agreements are enforceable among those who've agreed upon them.” It seems from the above that “all members of an organization” are included in the agreement binding, however, the statement “Agreements are enforceable among those who’ve agreed upon them” seems to conflict that. I can see four options: 
Either there are “sub” agreements (sub to those which affect all members), which only those affected by it must agree to. Or “those who’ve agreed upon them”’refers to all members. Or there is an alternative option I have not considered. Or I am missing a piece of information. Either way, it think it should be clarified or a distinction made between different types/scale of agreements (on an organizational, top-level agreement or a departmental level one)

Consensus: “Process of rational discourse” perhaps that should be elaborated. “Openly consider and investigate all alternatives proposed by members involved in the consensus process.” - should there not be any form of check in place to ensure that all members get an equal opportunity for discussion, and no member dominates the “rational discourse” process..? I suppose that would partially depend on what the format of rational discourse is. 

-“..new consensus can be reached on either the unamended or amended agreement” - What is the significance of including the words “unamended or amended agreement”?

Higher Authorities - “Authorities which hold monopolies on the use of violent force.” Please explain what is meant by “violent force”. 

Member - A member of an organization according to that organizations self-defined criteria for full membership. What about members who do not have full privileges, are they not referred to as a “member”? 

Moment of autocracy - “In the absence of a viable means of arriving at consensus, mandating the use of consensus driven processes as described in this repository should be viewed as legitimate, but only for that particular moment.” What exactly is “in the absence of viable means”? Who gets to decide that a situation qualifies for “in the absence of a viable means”? Also, what is “in that particular moment”? How “long” does that moment stretch, is the moment of autocracy for the entirety of the decision?

**Comment by rigelrozanski** [comment]
Closing this issue in favour of all the new linked sub-issues created
